---
title: Video Editor
---
classDiagram
    Cmd <|.. RevertableCmd
    Cmd <|.. UndoCmd
    RevertableCmd <|.. SetTextCmd
    RevertableCmd <|.. SetContrastCmd
    RevertableCmd <|.. RemoveTextCmd
    class Cmd{
        +execute() None
    }
    class RevertableCmd{
        +execute() None
        +unexecute() None
    }
    class VideoEditor{
        +__init__() None
        +set_text() None
        +remove_text() None
        +get_contrast() float
        +set_contrast() None
        +__str__() string
        
    }
    class History{
       +__init__() None
        +push() None
        +pop() RevertableCmd
        +__len__() int
    }
    class SetTextCmd{
       +__init__() None
        +execute() None
        +unexecute() None
    }
    class SetContrastCmd{
       +__init__() None
        +execute() None
        +unexecute() None
    }
    class RemoveTextCmd{
       +__init__() None
        +execute() None
        +unexecute() None
    }
    class UndoCmd{
       +__init__() None
        +execute() None
    }

